<?php
$auto_reviews_ship = array(
    array("name" => "Petr H.", "text" => "Nemusel jsem dlouho čekat, doručení proběhlo profesionálně."),
    array("name" => "Jan M.", "text" => "Doručení bylo mimořádně rychlé a všechny informace jsem dostal e-mailem i SMS. Obzvlášť se mi líbilo, že kurýr zavolal před příjezdem. Měl jsem pocit, že je vše organizováno přímo na míru zákazníkovi."),
    array("name" => "Stanislav P.", "text" => "Vše dorazilo včas, kurýr velmi milý."),
    array("name" => "Nikola V.", "text" => "Balení opravdu kvalitní, je vidět snaha."),
    array("name" => "Martin K.", "text" => "Balík dorazil nepoškozený a skvěle zabalený. Vše bylo chráněné tak, že nemohlo dojít k poškození během přepravy. Velká pochvala za profesionalitu."),
    array("name" => "Marek C.", "text" => "Doručovací služba bez chyby."),
    array("name" => "Leon T.", "text" => "Kurýr byl slušný a milý, doručení přesné na minutu. Balík byl úhledně zabalený a bez jakéhokoliv poškození. Jsem velmi spokojený."),
    array("name" => "Zdeněk T.", "text" => "Velmi rychlé doručení a skvělá koordinace."),
    array("name" => "Branislav S.", "text" => "Služba na vysoké úrovni, vše jasné."),
    array("name" => "Kristián O.", "text" => "Balení bylo velmi úhledné a bezpečné. Nebylo žádné poškození a doručení proběhlo v domluveném termínu. Ode mě jen pochvala."),
    array("name" => "Zdeněk J.", "text" => "Pečlivě zabaleno a bezpečně doručeno."),
    array("name" => "Tomáš R.", "text" => "Balík dorazil dříve než bylo plánováno."),
    array("name" => "Jan B.", "text" => "Vše dorazilo dříve, než jsem očekával."),
    array("name" => "Dominik C.", "text" => "Doručení bylo přesné a rychlé."),
    array("name" => "Zdeněk U.", "text" => "Doručení bylo rychlé a balení velmi pečlivé. Podpora byla dostupná i mimo pracovní dobu. Doporučuji každému, kdo chce bezstarostný nákup."),
    array("name" => "Milan C.", "text" => "Obal úhledný a kvalitní."),
    array("name" => "Zdeněk R.", "text" => "Zákaznická podpora rychle odpověděla na můj dotaz ohledně doručení. Balík dorazil dokonce dříve než bylo uvedeno na stránce. Rozhodně doporučuji."),
    array("name" => "Sasha L.", "text" => "Velmi jednoduché převzetí."),
    array("name" => "Tomáš P.", "text" => "Rychlé doručení a jednoduché převzetí."),
    array("name" => "David S.", "text" => "Velmi dobrá služba."),
    array("name" => "Martin H.", "text" => "Od objednávky po doručení vše proběhlo hladce. Vždy jsem měl přehled o stavu zásilky, což mi dodalo důvěru. Velmi kvalitní služba."),
    array("name" => "Petr V.", "text" => "Doručení bylo rychlé."),
    array("name" => "Filip P.", "text" => "Balík dorazil do 2 dnů, což mě velmi překvapilo. Balení bylo kvalitní a úhledné, přesně jak má být. Určitě objednám znovu."),
    array("name" => "Antonín F.", "text" => "Vše proběhlo hladce."),
    array("name" => "Mario D.", "text" => "Balík dorazil dříve než očekávaný termín."),
    array("name" => "Nikola J.", "text" => "Balík dorazil nepoškozený."),
    array("name" => "Blahoslav I.", "text" => "Objednání bylo jednoduché a doručení ještě jednodušší. Informace o sledování byly jasné a aktuální. Skvělá služba."),
    array("name" => "Jan K.", "text" => "Nemám žádné výhrady."),
    array("name" => "Dino A.", "text" => "Sledoval jsem doručení online a vše fungovalo bezchybně. Balík dorazil dříve a byl úhledně zabalený. Všechny informace byly dostupné včas."),
    array("name" => "Radek M.", "text" => "Všechny informace o sledování jsem dostal okamžitě."),
    array("name" => "Bohdan R.", "text" => "Balení úhledné, dorazilo bezpečně a bez poškození."),
    array("name" => "Andrej Z.", "text" => "Doručení bylo rychlejší, než bylo uvedeno."),
    array("name" => "Darko G.", "text" => "Podpora vždy dostupná."),
    array("name" => "Vladimír F.", "text" => "Neměl jsem žádné potíže, vše proběhlo hladce."),
    array("name" => "Jan Z.", "text" => "Zákaznická podpora byla velmi ochotná a rychle odpověděla. Doručení dorazilo dříve než bylo uvedeno v oznámení. Doporučuji."),
    array("name" => "Alan V.", "text" => "Jsem velmi spokojený."),
    array("name" => "Miroslav B.", "text" => "Velmi rychlé doručení."),
    array("name" => "Josef G.", "text" => "Úhledně zabaleno a rychle doručeno."),
    array("name" => "Radek D.", "text" => "Po objednání šlo vše velmi rychle. Balík byl připraven a odeslán ještě ten den a dorazil už následující den. Skvělá zkušenost."),
    array("name" => "Nino T.", "text" => "Rychlé zpracování objednávky, skvělé."),
    array("name" => "Antonín H.", "text" => "Takto profesionální služba se vidí málokdy."),
    array("name" => "Goran J.", "text" => "Objednal jsem v pondělí a balík dorazil už ve středu. Celý proces byl jednoduchý a přehledný. Jsem velmi spokojený."),
    array("name" => "Nikola T.", "text" => "Doručení bylo rychlejší, než jsem očekával. Dostal jsem oznámení v každé fázi, což mi dodalo důvěru. Velmi profesionální služba."),
    array("name" => "Alan F.", "text" => "Balík dorazil dříve."),
    array("name" => "Marek Z.", "text" => "Celý proces doručení byl jednoduchý."),
    array("name" => "Jan L.", "text" => "Ihned po objednávce jsem dostal potvrzení a číslo pro sledování. Balík dorazil nepoškozený a včas. Služba si zaslouží jedničku."),
    array("name" => "Kristián N.", "text" => "Balík dorazil v perfektním stavu."),
    array("name" => "Marián D.", "text" => "Mám jen slova chvály – od objednávky po doručení vše proběhlo profesionálně. Kurýr mi zavolal před doručením a vše proběhlo bez stresu. Skvělá práce."),
    array("name" => "Matěj R.", "text" => "Sledování zásilky fungovalo skvěle."),
    array("name" => "Petr L.", "text" => "Balík dorazil úhledně zabalený a rychle doručený."),
    array("name" => "Lukáš F.", "text" => "Vše proběhlo bez stresu – objednávka, potvrzení i doručení. Balík byl bezpečně zabalený a dorazil včas. Skvělá služba."),
    array("name" => "Zdeněk O.", "text" => "Vše proběhlo hladce a rychle."),
    array("name" => "Mario E.", "text" => "Oceňuji, že byl kurýr slušný a zavolal před příjezdem. Nemusel jsem ztrácet čas, vše bylo domluveno předem. Velmi příjemná zkušenost."),
    array("name" => "René K.", "text" => "Kurýr byl velmi ochotný."),
    array("name" => "Nikša B.", "text" => "Vše proběhlo hladce a úhledně."),
    array("name" => "Zoran J.", "text" => "Pochvala zákaznické podpoře, dotaz vyřešen rychle."),
    array("name" => "David L.", "text" => "Kurýr zavolal před doručením, skvělá organizace."),
    array("name" => "Petr R.", "text" => "Kurýr byl milý a profesionální. Balík dorazil bez problémů. Velmi pozitivní zkušenost."),
    array("name" => "Štěpán H.", "text" => "Kurýr byl ochotný."),
    array("name" => "Václav D.", "text" => "Doručení rychlé a úhledné."),
    array("name" => "Marián K.", "text" => "Doručení bylo rychlé a úhledné, balík bez poškození."),
    array("name" => "Boris I.", "text" => "Doručovací služba výborná."),
    array("name" => "Antonín V.", "text" => "Balík dorazil úhledně zabalený a bez poškození. Obal byl pevný a kvalitní. Bylo vidět, že se dbá na detaily."),
    array("name" => "Štěpán P.", "text" => "Kurýr mě kontaktoval před doručením."),
    array("name" => "Jan J.", "text" => "Úhledně zabaleno, velká pochvala."),
    array("name" => "Damian E.", "text" => "Velká pochvala za rychlost a přesnost."),
    array("name" => "Darko O.", "text" => "Vše proběhlo přesně podle uvedených informací."),
    array("name" => "Nikola H.", "text" => "Vše úhledné a přesné."),
    array("name" => "Blahoslav P.", "text" => "Velká pochvala."),
    array("name" => "Sven K.", "text" => "Vše skvělé."),
    array("name" => "Goran F.", "text" => "Kurýr byl přesný a milý."),
    array("name" => "Tomáš Z.", "text" => "Vše bylo skvělé."),
    array("name" => "Mario J.", "text" => "Nemusel jsem dlouho čekat."),
    array("name" => "Slavomír J.", "text" => "Celý proces objednávky a doručení byl příjemný."),
    array("name" => "Matěj C.", "text" => "Doručení super."),
    array("name" => "Kristián E.", "text" => "Doručení úhledné."),
    array("name" => "Jan M.", "text" => "Vše bylo transparentní a jasné."),
    array("name" => "Lukáš B.", "text" => "Všechny informace byly dostupné."),
    array("name" => "Josef D.", "text" => "Všechny informace o doručení byly jasné."),
    array("name" => "Nenad B.", "text" => "Balení pevné a bezpečné, velká pochvala."),
    array("name" => "Miloslav R.", "text" => "Dorazilo rychle."),
    array("name" => "Sasha D.", "text" => "Kurýr byl velmi korektní."),
    array("name" => "Leon M.", "text" => "Vše dorazilo úhledně a včas."),
    array("name" => "Zdeněk M.", "text" => "Balík dorazil včas."),
    array("name" => "Kristián V.", "text" => "Obal kvalitní, balík nepoškozený."),
    array("name" => "Lukáš N.", "text" => "Velká pochvala za službu."),
    array("name" => "Alan K.", "text" => "Kurýr byl velmi profesionální."),
    array("name" => "Jan T.", "text" => "Obal velmi kvalitní."),
    array("name" => "Antonín G.", "text" => "Balení pevné."),
    array("name" => "Marin G.", "text" => "Výborná komunikace s podporou."),
    array("name" => "David O.", "text" => "Doručení bylo mimořádně rychlé."),
    array("name" => "Robert E.", "text" => "Balení úhledné a pevné."),
    array("name" => "Filip M.", "text" => "Vše proběhlo jednoduše a bez komplikací."),
    array("name" => "Antonín I.", "text" => "Po objednávce jsem okamžitě obdržel všechny potřebné údaje pro sledování. Doručení bylo přesné a úhledné. Skvělá organizace."),
    array("name" => "Marek P.", "text" => "Doručení rychlé, vše úhledně složené a zabalené."),
    array("name" => "Zdeněk K.", "text" => "Celý proces doručení byl velmi transparentní. Dostal jsem oznámení o každé fázi. Bez stresu, vše funguje skvěle."),
    array("name" => "Srečko G.", "text" => "Služba výborná, kurýr velmi profesionální."),
    array("name" => "Bruno Z.", "text" => "Vše dorazilo přesně včas."),
    array("name" => "Slavomír P.", "text" => "Vše kolem doručení proběhlo hladce. Kurýr byl milý a přesný, balík úhledně zabalený. Jsem velmi spokojený."),
    array("name" => "Lukáš J.", "text" => "Doručení rychlé, kurýr milý a balík v pořádku."),
    array("name" => "Miloslav S.", "text" => "Kurýr byl velmi milý."),
    array("name" => "Antonín K.", "text" => "Všechny fáze doručení byly jasně komunikovány. Balík dorazil dříve a byl dobře zabalený. Velmi pozitivní zkušenost."),
    array("name" => "Dominik N.", "text" => "Podpora dostupná i o víkendu, velká pochvala."),
    array("name" => "Filip K.", "text" => "Sledování zásilky fungovalo perfektně."),
    array("name" => "Lukáš C.", "text" => "Vše jasné a úhledné, dorazilo bez zpoždění."),
    array("name" => "Karel P.", "text" => "Velmi jednoduché převzetí."),
    array("name" => "Václav C.", "text" => "Rychlé a spolehlivé doručení."),
    array("name" => "Petr V.", "text" => "Vše proběhlo bez jakýchkoliv problémů."),
    array("name" => "Antonín I.", "text" => "Doručení proběhlo bezchybně. Kurýr byl velmi milý a zavolal před příjezdem. Velká pochvala celému týmu."),
    array("name" => "Lukáš C.", "text" => "Vše dorazilo bez zpoždění."),
    array("name" => "Robert N.", "text" => "Podpora mě o všem informovala."),
    array("name" => "Zdeněk E.", "text" => "Obvykle jsem k recenzím skeptický, ale zde vše odpovídá realitě."),
    array("name" => "Martin T.", "text" => "Neměl jsem žádné problémy."),
    array("name" => "Mario L.", "text" => "Balík dorazil nepoškozený a úhledný."),
    array("name" => "Andrej P.", "text" => "Vše proběhlo jednoduše a rychle. Doručení včas a bez problémů. Určitě doporučuji."),
    array("name" => "Lukáš N.", "text" => "Velká pochvala za službu."),
    array("name" => "Miloslav K.", "text" => "Doručení bylo velmi rychlé a kurýr slušný. Balík dorazil ve skvělém stavu. Doporučuji."),
    array("name" => "Toni H.", "text" => "Velmi jednoduchý proces objednávky."),
    array("name" => "Vědron R.", "text" => "Nečekal jsem dlouho, vše dorazilo rychle."),
    array("name" => "Marián L.", "text" => "Vše bylo rychlé a jednoduché. Balík v pořádku, doručení rychlé a bezpečné. Velmi pozitivní zkušenost."),
    array("name" => "Miloslav S.", "text" => "Kurýr byl velmi milý."),
);
?>